apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deployment
  namespace: go-app-namespace
  labels:
    app: go-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      imagePullSecrets:
        - name: go-app-registry  # Name of the secret you created
      containers:
      - name: go-app
        image: emafzal/go-app:v1
        ports:
        - containerPort: 8080
